using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace MyCustomizedFramework.Cli.Writing;

/// <summary>
/// Keeps a single barrel (features/routes.generated.ts) listing every generated feature's routes,
/// so the host app wires routing once instead of once per table. Always rewritten from what is on disk.
/// </summary>
internal static class FrontendRoutesBarrel
{
    public const string FileName = "routes.generated.ts";

    public const string NavFileName = "nav.generated.ts";

    public static string? Write(string webRoot, string framework)
    {
        var featuresDir = Path.Combine(webRoot, "features");
        if (!Directory.Exists(featuresDir))
        {
            return null;
        }

        var extension = framework == "react" ? ".routes.tsx" : ".routes.ts";
        var features = Directory.GetDirectories(featuresDir)
            .Select(dir => Path.GetFileName(dir))
            .Where(folder => File.Exists(Path.Combine(featuresDir, folder, folder + extension)))
            .OrderBy(folder => folder, StringComparer.Ordinal)
            .ToArray();

        if (features.Length == 0)
        {
            return null;
        }

        var (typeImport, typeName) = framework switch
        {
            "angular" => ("import type { Routes } from '@angular/router';", "Routes"),
            "vue" => ("import type { RouteRecordRaw } from 'vue-router';", "RouteRecordRaw[]"),
            _ => ("import type { RouteObject } from 'react-router-dom';", "RouteObject[]")
        };

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated> Rewritten by crudgen on every run; do not edit. </auto-generated>");
        builder.AppendLine(typeImport);
        foreach (var folder in features)
        {
            builder.AppendLine(System.Globalization.CultureInfo.InvariantCulture, $"import {{ {ToCamel(folder)}Routes }} from './{folder}/{folder}.routes';");
        }

        builder.AppendLine();
        builder.AppendLine(System.Globalization.CultureInfo.InvariantCulture, $"export const featureRoutes: {typeName} = [");
        foreach (var folder in features)
        {
            builder.AppendLine(System.Globalization.CultureInfo.InvariantCulture, $"  ...{ToCamel(folder)}Routes,");
        }

        builder.AppendLine("];");

        var path = Path.Combine(featuresDir, FileName);
        File.WriteAllText(path, builder.ToString());
        WriteNav(featuresDir, features, extension);
        return path;
    }

    private static void WriteNav(string featuresDir, string[] features, string extension)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated> Rewritten by crudgen on every run; do not edit. </auto-generated>");
        builder.AppendLine("export interface FeatureNavItem {");
        builder.AppendLine("  readonly label: string;");
        builder.AppendLine("  readonly path: string;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("export const featureNav: readonly FeatureNavItem[] = [");

        foreach (var folder in features)
        {
            var routes = File.ReadAllText(Path.Combine(featuresDir, folder, folder + extension));
            var match = Regex.Match(routes, "path:\\s*['\"]/?([^'\"/:]+)['\"]");
            if (!match.Success)
            {
                continue;
            }

            var label = string.Join(' ', folder.Split('-', StringSplitOptions.RemoveEmptyEntries)
                .Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
            builder.AppendLine(CultureInfo.InvariantCulture, $"  {{ label: '{label}', path: '/{match.Groups[1].Value}' }},");
        }

        builder.AppendLine("];");
        File.WriteAllText(Path.Combine(featuresDir, NavFileName), builder.ToString());
    }

    private static string ToCamel(string kebab)
    {
        var parts = kebab.Split('-', StringSplitOptions.RemoveEmptyEntries);
        return parts[0] + string.Concat(parts.Skip(1).Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
    }
}


